# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\近义词抽查项目\近义词抽查界面\开始界面.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SynonymSpotCheckProgram(object):
    def setupUi(self, SynonymSpotCheckProgram):
        SynonymSpotCheckProgram.setObjectName("SynonymSpotCheckProgram")
        SynonymSpotCheckProgram.resize(241, 501)
        self.centralwidget = QtWidgets.QWidget(SynonymSpotCheckProgram)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 110, 211, 321))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        SynonymSpotCheckProgram.setCentralWidget(self.centralwidget)

        self.retranslateUi(SynonymSpotCheckProgram)
        QtCore.QMetaObject.connectSlotsByName(SynonymSpotCheckProgram)

    def retranslateUi(self, SynonymSpotCheckProgram):
        _translate = QtCore.QCoreApplication.translate
        SynonymSpotCheckProgram.setWindowTitle(_translate("SynonymSpotCheckProgram", "MainWindow"))
        self.pushButton.setText(_translate("SynonymSpotCheckProgram", "单词抽查"))
        self.pushButton_2.setText(_translate("SynonymSpotCheckProgram", "近义词抽查"))
        self.pushButton_4.setText(_translate("SynonymSpotCheckProgram", "设置"))
        self.pushButton_3.setText(_translate("SynonymSpotCheckProgram", "退出"))
