# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Program\PythonProgram\近义词抽查项目\近义词抽查界面\近义词抽查界面.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1137, 689)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setGeometry(QtCore.QRect(0, -50, 1231, 841))
        self.frame_8.setStyleSheet("QFrame{\n"
"background-color:rgb(30,31,34)\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setGeometry(QtCore.QRect(10, 10, 961, 61))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setGeometry(QtCore.QRect(30, 70, 1071, 401))
        self.frame_11.setAutoFillBackground(False)
        self.frame_11.setStyleSheet("QPushButton{\n"
"height:120px;\n"
"background-color:rgb(160,160,160);\n"
"border-radius:25px;\n"
"border:none;\n"
"color:rgb(255,255,255);\n"
"font-size:50px;\n"
"font-style:none;\n"
"font: 57 35pt \"Adobe Myungjo Std M\";\n"
"}\n"
"QPushButton::hover{\n"
"background-color:rgb(65,200,255)\n"
"}")

        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setLineWidth(0)
        self.frame_11.setObjectName("frame_11")
        self.frame_17 = QtWidgets.QFrame(self.frame_11)
        self.frame_17.setGeometry(QtCore.QRect(0, 139, 1071, 261))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_14 = QtWidgets.QFrame(self.frame_17)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setLineWidth(0)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_option_1 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_option_1.setStyleSheet("")
        self.pushButton_option_1.setObjectName("pushButton_option_1")
        self.verticalLayout.addWidget(self.pushButton_option_1)
        self.pushButton_option_3 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_option_3.setObjectName("pushButton_option_3")
        self.verticalLayout.addWidget(self.pushButton_option_3)
        self.horizontalLayout_8.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_17)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setLineWidth(0)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_option_2 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_option_2.setObjectName("pushButton_option_2")
        self.verticalLayout_5.addWidget(self.pushButton_option_2)
        self.pushButton_option_4 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_option_4.setObjectName("pushButton_option_4")
        self.verticalLayout_5.addWidget(self.pushButton_option_4)
        self.horizontalLayout_8.addWidget(self.frame_15)
        self.label_problem = QtWidgets.QLabel(self.frame_11)
        self.label_problem.setGeometry(QtCore.QRect(250, 10, 571, 111))
        self.label_problem.setStyleSheet("QLabel{\n"
"font-size:30px;\n"
"background-color:rgb(160,160,160);\n"
"text-align:center;\n"
"border-radius:20px;\n"
"color:rgb(255,255,255);\n"
"font: 57 36pt \"Adobe Myungjo Std M\";\n"
"}")
        self.label_problem.setObjectName("label_problem")
        self.frame_12 = QtWidgets.QFrame(self.frame_8)
        self.frame_12.setGeometry(QtCore.QRect(30, 480, 541, 231))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.textBrowser_translation = QtWidgets.QTextBrowser(self.frame_12)
        self.textBrowser_translation.setGeometry(QtCore.QRect(0, 10, 531, 211))
        self.textBrowser_translation.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.textBrowser_translation.setMouseTracking(False)
        self.textBrowser_translation.setStyleSheet("QTextBrowser{\n"
"font-size:50px;\n"
"background-color:rgb(160,160,160);\n"
"border-radius:25px;\n"
"color:rgb(255,255,255);\n"
"font: 25 40pt \"Adobe 宋体 Std L\";\n"
"}")
        self.textBrowser_translation.setObjectName("textBrowser_translation")
        self.frame_13 = QtWidgets.QFrame(self.frame_8)
        self.frame_13.setGeometry(QtCore.QRect(570, 490, 531, 211))
        self.frame_13.setStyleSheet("QPushButton{\n"
"height:120px;\n"
"background-color:rgb(160,160,160);\n"
"border-radius:25px;\n"
"border:none;\n"
"font-size:50px;\n"
"font-style:none;\n"
"color:rgb(255,255,255);\n"
"font: 25 \"Adobe 宋体 Std L\";\n"
"}\n"
"QPushButton::hover{\n"
"background-color:rgb(70,203,255)\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.pushButton_translation = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_translation.setGeometry(QtCore.QRect(0, 10, 531, 81))
        self.pushButton_translation.setObjectName("pushButton_translation")
        self.pushButton_next = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_next.setGeometry(QtCore.QRect(0, 110, 531, 81))
        self.pushButton_next.setObjectName("pushButton_next")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_option_1.setText(_translate("MainWindow", "选项1"))
        self.pushButton_option_3.setText(_translate("MainWindow", "选项3"))
        self.pushButton_option_2.setText(_translate("MainWindow", "选项2"))
        self.pushButton_option_4.setText(_translate("MainWindow", "选项4"))
        self.label_problem.setText(_translate("MainWindow", "所抽查的单词英文"))
        self.pushButton_translation.setText(_translate("MainWindow", "查看中文意思"))
        self.pushButton_next.setText(_translate("MainWindow", "下一题"))
